i  This command links your local project to Firebase App Hosting. You will be able to deploy your web app with `firebase deploy` after setup. ✔ Please select an option Link to an existing backend ✔ Which backend would you like to link? my-web-app i  === Deploy local source setup ✔ Specify your app's root directory relative to your firebase.json directory / i  Writing configuration info to firebase.json... i  Writing default settings to apphosting.yaml... i  /home/user/studio/apphosting.yaml is unchanged ✔  Firebase initialization complete!
=== Hosting Setup

Your public directory is the folder (relative to your project directory) that
will contain Hosting assets to be uploaded with firebase deploy. If you
have a build process for your assets, use your build's output directory.

✔ What do you want to use as your public directory? public
✔ Configure as a single-page app (rewrite all urls to /index.html)? Yes
✔ Set up automatic builds and deploys with GitHub? No
i  public/index.html is unchanged

=== Storage Setup

Firebase Storage Security Rules allow you to define how and when to allow
uploads and downloads. You can keep these rules in your project directory
and publish them with firebase deploy.

✔ What file should be used for Storage Rules? storage.rules
✔  Wrote storage.rules

=== Remoteconfig Setup
✔ What file should be used for your Remote Config template? remoteconfig.template.json

=== Database Setup
i  database: ensuring required API firebasedatabase.googleapis.com is enabled...
⚠  database: missing required API firebasedatabase.googleapis.com. Enabling now...
✔  database: required API firebasedatabase.googleapis.com is enabled

✔ It seems like you haven’t initialized Realtime Database in your project yet. Do you want to set it up? Yes
✔ Please choose the location for your default Realtime Database instance: us-central1
✔ Creating your default Realtime Database instance: hustlepay-10088-default-rtdb

Firebase Realtime Database Security Rules allow you to define how your data should be
structured and when your data can be read from and written to.

✔ What file should be used for Realtime Database Security Rules? database.rules.json
✔  Database Rules for hustlepay-10088 have been written to database.rules.json.
Future modifications to database.rules.json will update Realtime Database Security Rules when you run
firebase deploy.

i  Writing configuration info to firebase.json...
i  Writing project information to .firebaserc...

✔  Firebase initialization complete!
studio-274307878:~/studio{master}$ firebase deploy

=== Deploying to 'hustlepay-10088'...

i  deploying database, storage, firestore, functions, hosting, remoteconfig, dataconnect, apphosting
i  database: checking rules syntax...
✔  database: rules syntax for database hustlepay-10088-default-rtdb is valid
i  storage: ensuring required API firebasestorage.googleapis.com is enabled...
✔  storage: required API firebasestorage.googleapis.com is enabled
i  firebase.storage: checking storage.rules for compilation errors...
✔  firebase.storage: rules file storage.rules compiled successfully
i  firestore: reading indexes from firestore.indexes.json...
i  cloud.firestore: checking firestore.rules for compilation errors...
✔  cloud.firestore: rules file firestore.rules compiled successfully
i  functions: preparing codebase default for deployment
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
i  artifactregistry: ensuring required API artifactregistry.googleapis.com is enabled...
✔  functions: required API cloudfunctions.googleapis.com is enabled
✔  artifactregistry: required API artifactregistry.googleapis.com is enabled
✔  functions: required API cloudbuild.googleapis.com is enabled

Error: There was an error reading functions/package.json:

 functions/lib/index.js does not exist, can't deploy Cloud Functions
studio-274307878:~/studio{master}$