✔ Which connector do you want set up a generated SDK for? studio/default i  Detected react app. Enabling react generated SDKs. ✔ Which frameworks would you like to generate SDKs for? Press Space to select features, then Enter to confirm your choices. react i  Writing your new SDK configuration to /home/user/studio/dataconnect/connector/connector.yaml i  dataconnect/connector/connector.yaml is unchanged [winston] Unknown logger level: DEBUG I0522 07:50:46.254897   13194 codegen.go:82] [connector "default" javascriptSdk] Generating sources into "/home/user/studio/dataconnect-generated/js/default-connector" I0522 07:50:46.272722   13194 generate.go:40] Generated all sources. Writing them to disk... I0522 07:50:46.275039   13194 collector.go:107] connector "default" javascriptSdk wrote into "/home/user/studio/dataconnect-generated/js/default-connector" Generated sources: esm/index.esm.js [109B] esm/package.json [17B] index.cjs.js [144B] README.md [2774B] react/index.d.ts [228B] react/esm/package.json [17B] react/index.cjs.js [0B] react/README.md [5357B] index.d.ts [246B] package.json [860B] react/package.json [468B] react/esm/index.esm.js [0B] I0522 07:50:46.283425   13194 installsdk.go:49] Package @firebasegen/default-connector is already installed. Skipping installation
i  Generated SDK code for default
i  Visit https://firebase.google.com/docs/data-connect/web-sdk#react for more information on how to set up React Generated SDKs for Firebase Data Connect
✔  If you'd like to add more generated SDKs to your app your later, run firebase init dataconnect:sdk again

=== Firestore Setup

Firestore Security Rules allow you to define how and when to allow
requests. You can keep these rules in your project directory
and publish them with firebase deploy.

✔ What file should be used for Firestore Rules? firestore.rules
✔ File firestore.rules already exists. Do you want to overwrite it with the Firestore Rules from the Firebase Console? No

Firestore indexes allow you to perform complex queries while
maintaining performance that scales with the size of the result
set. You can keep index definitions in your project directory
and publish them with firebase deploy.

✔ What file should be used for Firestore indexes? firestore.indexes.json
✔ File firestore.indexes.json already exists. Do you want to overwrite it with the Firestore Indexes from the Firebase Console? No

=== Functions Setup
Let's create a new codebase for your functions.
A directory corresponding to the codebase will be created in your project
with sample code pre-configured.

See https://firebase.google.com/docs/functions/organize-functions for
more information on organizing your functions using codebases.

Functions can be deployed with firebase deploy.

✔ What language would you like to use to write Cloud Functions? JavaScript
✔ Do you want to use ESLint to catch probable bugs and enforce style? No
✔ File functions/package.json already exists. Overwrite? No
i  Skipping write of functions/package.json
i  functions/index.js is unchanged
✔ File functions/.gitignore already exists. Overwrite? No
i  Skipping write of functions/.gitignore
✔ Do you want to install dependencies with npm now? No

=== App Hosting Setup
i  This command links your local project to Firebase App Hosting. You will be able to deploy your web app with `firebase deploy` after setup.
✔ Please select an option Create a new backend
i  === Set up your backend
✔ Select a primary region to host your backend:
 us-central1
✔  Location set to us-central1.

✔ Provide a name for your backend [1-30 characters] HustlePay
✔  Name set to HustlePay

⚠  Unable to create a new web app, the project has reached the quota for Firebase apps. Navigate to your Firebase console to manage or delete a Firebase app to continue.
⚠  Firebase web app not set
⠧ Creating your new backend...
Error: Request to https://firebaseapphosting.googleapis.com/v1beta/projects/hustlepay-10088/locations/us-central1/backends?backendId=HustlePay had HTTP Error: 400, The request was invalid: Violation in CreateBackendRequest.backend_id: only lowercase, digits, and hyphens; must begin with letter, and cannot end with hyphen;
⠋ Creating your new backend...
Having trouble? Try firebase [command] --help
studio-274307878:~/studio{master}$ npm install firebase
npm warn ERESOLVE overriding peer dependency
npm warn While resolving: @firebasegen/default-connector@1.0.0
npm warn Found: @tanstack-query-firebase/react@1.0.6
npm warn node_modules/@tanstack-query-firebase/react
npm warn   @tanstack-query-firebase/react@"^1.0.5" from the root project
npm warn
npm warn Could not resolve dependency:
npm warn peer @tanstack-query-firebase/react@"^2.0.0" from @firebasegen/default-connector@1.0.0
npm warn dataconnect-generated/js/default-connector
npm warn   @firebasegen/default-connector@1.0.0
npm warn   node_modules/@firebasegen/default-connector
npm warn
npm warn Conflicting peer dependency: @tanstack-query-firebase/react@2.0.0
npm warn node_modules/@tanstack-query-firebase/react
npm warn   peer @tanstack-query-firebase/react@"^2.0.0" from @firebasegen/default-connector@1.0.0
npm warn   dataconnect-generated/js/default-connector
npm warn     @firebasegen/default-connector@1.0.0
npm warn     node_modules/@firebasegen/default-connector

added 1 package, removed 1 package, changed 30 packages, and audited 741 packages in 48s

98 packages are looking for funding
  run `npm fund` for details

2 vulnerabilities (1 low, 1 moderate)

To address issues that do not require attention, run:
  npm audit fix

To address all issues, run:
  npm audit fix --force

Run `npm audit` for details.
studio-274307878:~/studio{master}$